# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20180318_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='value',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
