# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_mipsprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipsprogram',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
