# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_auto_20180320_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasegment',
            name='name',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='mipsprogram',
            name='name',
            field=models.IntegerField(max_length=4),
        ),
    ]
