# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_auto_20180327_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasegment',
            name='name',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mipsprogram',
            name='name',
            field=models.IntegerField(default=0),
        ),
    ]
