# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_auto_20180327_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasegment',
            name='value',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
