# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_memoryclearer'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryclearer',
            name='memoryType',
            field=models.IntegerField(default=0),
        ),
    ]
