# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0012_memoryclearer_memorytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=2, null=True)),
                ('instruction', models.CharField(blank=True, max_length=6, null=True)),
                ('rd', models.CharField(blank=True, max_length=2, null=True)),
                ('rs', models.CharField(blank=True, max_length=2, null=True)),
                ('rt', models.CharField(blank=True, max_length=2, null=True)),
                ('offset', models.CharField(blank=True, max_length=4, null=True)),
                ('immediate', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
