# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0013_pipelineinstructions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PipelineInstructions',
            new_name='PipelineInstruction',
        ),
    ]
