# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0015_auto_20180408_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='EX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('opcode', models.CharField(blank=True, max_length=8, null=True)),
                ('aluoutput', models.IntegerField(default=0)),
                ('cond', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('opcode', models.CharField(blank=True, max_length=8, null=True)),
                ('a', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('imm', models.IntegerField(default=0)),
                ('npc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('opcode', models.CharField(blank=True, max_length=8, null=True)),
                ('npc', models.IntegerField(default=0)),
                ('pc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('opcode', models.CharField(blank=True, max_length=8, null=True)),
                ('lmd', models.IntegerField(default=0)),
                ('aluoutput', models.IntegerField(default=0)),
                ('memoryrange', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('opcode', models.CharField(blank=True, max_length=8, null=True)),
                ('result', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PipelineInstruction',
        ),
    ]
