# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0017_auto_20180411_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='id',
            old_name='npc',
            new_name='ir',
        ),
        migrations.RenameField(
            model_name='if',
            old_name='npc',
            new_name='ir',
        ),
        migrations.AddField(
            model_name='ex',
            name='ir',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mem',
            name='ir',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
