# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0019_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='POSITION',
            new_name='AFTER',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='SPACE',
            new_name='AFTERSPACE',
        ),
        migrations.AddField(
            model_name='table',
            name='BEFORE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='BEFORESPACE',
            field=models.IntegerField(default=0),
        ),
    ]
