# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0021_auto_20180411_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='BEFORESPACE',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
