# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0022_auto_20180411_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='memoryComparer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameInt', models.IntegerField(default=0)),
                ('nameHex', models.CharField(max_length=4)),
            ],
        ),
    ]
