# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0024_memorycomparer_memorytype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='memoryComparer',
        ),
        migrations.AddField(
            model_name='datasegment',
            name='nameHex',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='mipsprogram',
            name='nameHex',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
